export enum Role {
  ADMIN = 'ADMIN',
  TRANSLATOR = 'TRANSLATOR',
}

export enum UpdateUserOperation {
  UPDATE_PASSWORD = 'UPDATE_PASSWORD',
  UPDATE_LANGUAGES = 'UPDATE_LANGUAGES',
  UPDATE_API_KEY = 'UPDATE_API_KEY',
}
